trigger:
  - main


variables:
  myVariable: true

jobs:
- job: MyJob
  steps:
  - script: echo This task will always run
  
  - script: echo This task will only run if myVariable is true
    condition: eq(variables['myVariable'], 'true')

  - script: echo This task will always run