trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: ec " Task 1'
    displayName: 'Task 1'


  - script: ec 'Task 2'
    displayName: 'Task 2'


  - script: echo 'AuditLog'
    displayName: 'AuditLog'
    condition: failed()

